= Mmadu User Guide
Oyudo Gerald <gerald.oyudo@gmail.com>
v0.0.1, 2018-09-04
:toc:
:sectnums:
:showtitle:
:page-navtitle: Mmadu User Guide
:page-excerpt: User Guide
:page-root: ../
:imagesdir: {page-root}/images
:permalink: /:title/
:page-layout: api
:snippets: snippets

== Overview

=== What is Mmadu?

Mmadu (pronounced um-a-du) is derived from an Igbo word meaning people.

Have you ever found yourself in a state of deja-vu when ever you write user management logic? Mmadu provides
a set of tools that ensures that you never have to repeat user management logic. It helps to manage users, takes
care of registration work flows and exposes API's for authentication.

With Mmadu, you can have a dedicated system for managing users across all your applications.

=== Features

==== User Authentication

By calling an API, you can authenticate users of your application with Mmmadu. By passing a username
and password (can be encrypted) the rest api can determine whether the username/password combination is correct,
has correct username, or has incorrect password. You can integrate this rest api with a lot of web application frameworks.

==== Domain Management

By creating an managing domains, you can logically separate users. Users in a domain are used for only one application.
My storing users in multiple domains, you can use a single mmadu installation to
manage users across multiple applications.

==== User Management

The user service provides basic CRUD operations to help you manage and query your users.

==== Token Management

Mmadu utilizes tokens to secure its API's. You can create tokens that can only access one domain or utilize the admin token
which has access to all domains.

==== User Registration

Mmadu provides the web logic for registering users. With configured fields and field types, the registration api generates
dynamic and configurable registration forms that the client can use.

=== What's New

|===
|Version |Features

|v1.3.0
|
- Introduced user registration

- Added docker installation features

|v1.1.0
|
- User management API redesigned and made user friendly

- Bug fixes


|v1.0.0
|
- Domain and user management API was introduced

- Token security for domain and user management API was introduced.

|v0.0.1
|
- Api for creating and updating user information created.

- Api for authenticating username and password information has been created.
|===

=== Getting Started

Mmadu can be installed in a number of ways since it is built and distributed with jar files. The easiest way to install
mmadu is using docker.

====  Getting Started with Docker

===== Requirements

* Docker
* Docker Compose

===== Installation
. Create a folder (we will use mmadu as the created folder)
+
[source,sh]
----
mkdir mmadu && cd mmadu
----
. Download the https://raw.githubusercontent.com/geraldoyudo/mmadu/develop/docker/docker-compose.yml[docker compose file]
+
[source,sh]
----
wget https://raw.githubusercontent.com/geraldoyudo/mmadu/develop/docker/docker-compose.yml
----
. Download the https://raw.githubusercontent.com/geraldoyudo/mmadu/develop/docker/.env[default environment file]
+
[source,sh]
----
wget https://raw.githubusercontent.com/geraldoyudo/mmadu/develop/docker/.env
----
. Make the necessary modifications to suite your configuration (you can use it as is)
. Start the services
+
[source,sh]
----
docker-compose up
----

===== Using the default settings

The docker compose installation comes pre-configured with default settings. You can access the api from each service using
the default admin token 2222. The user management service, registration service and token service are
at ports 15551, 15552 and 15553 respectively.

===== Using the services

To find out more about how to consume the service API, please see <<API>>

== Architecture

Mmadu is built using a service oriented architecture. It is designed in such a manner that you utilize functionalities
by deploying the adequate services.

The core service is the user management service which handles authentication, user and domain management. The token service
is used by all other services for token authentication.

Currently, mmadu has the following services:


|===
|Service |Description

|Token Service
|Service for managing and checking tokens and permissions.

|User management Service
|Manages domain authentication as well as administration of domains and users.

|Registration Service
|Provides a dynamic registration form for each domain. Exposes API endpoints to configure registration form fields.
|===

== API

=== Security

If token security is enabled, you will need a token to access the api.

Simply set the domain-auth-token header to the value of the token. For more information on tokens, see token management.

==== Permissions

Some tokens have admin permissions, while others have domain permissions. Admin tokens can access all parts of the API,
while domain tokens can only access parts of the api that returns resources pertaining to the domain.

=== Token Service

Mmadu service uses token based security. Access to API can be done using admin and domain tokens. The default
port for the token service is 15553

==== Admin Token

An admin token is automatically created with an id "admin-token". This token will grant you access
to all resources in the API.

==== Domain Tokens

Domain tokens are created and assigned to a domain configuration. Every domain can have one domain token.
Multiple domains can share a domain token. Domain token grants the API user access to user resources for that domain.

==== Token Encryption

If encryption is enabled, the token values will be encrypted before storing in the database. It uses an AES CBC cipher to
encrypt token values.

Encryption can be enabled by setting the environment property `mmadu.domain.encrypt-keys` to `true`.

Token values are encrypted under the master-key.

===== Changing the Encryption Master Key

To change the encryption master key, set the environment property `mmadu.security.master-key` to the desired value.

==== Generating a Token

A GET request will create a new token and return the token value. If token encryption is enabled, the token value returned is
encrypted.

===== Request

include::{snippets}/token-management-documentation/generate-token/1/http-request.adoc[]

===== Response Fields

This API returns the newly generated token

include::{snippets}/token-management-documentation/generate-token/1/response-fields.adoc[]

Example:

include::{snippets}/token-management-documentation/generate-token/1/http-response.adoc[]

==== Retrieving a Token

A GET request will get a token with the ID.

===== Path Parameters

include::{snippets}/token-management-documentation/retrieve-token/1/path-parameters.adoc[]

Example:

include::{snippets}/token-management-documentation/retrieve-token/1/http-request.adoc[]


===== Response Fields

This API returns an AppUser with these fields:

include::{snippets}/token-management-documentation/retrieve-token/1/response-fields.adoc[]

Example:

include::{snippets}/token-management-documentation/retrieve-token/1/http-response.adoc[]

==== Resetting a Token

A GET request will generate a new token value for the token.

===== Path Parameters

include::{snippets}/token-management-documentation/reset-token/1/path-parameters.adoc[]

Example:

include::{snippets}/token-management-documentation/reset-token/1/http-request.adoc[]


===== Response Fields

This API returns a token with the following fields:

include::{snippets}/token-management-documentation/reset-token/1/response-fields.adoc[]

Example:

include::{snippets}/token-management-documentation/reset-token/1/http-response.adoc[]

==== Setting a Domain Token

A POST request will assign a token to a domain.

===== Request Fields

include::{snippets}/token-management-documentation/set-auth-token-for-domain/1/request-fields.adoc[]

Example:

include::{snippets}/token-management-documentation/set-auth-token-for-domain/1/http-request.adoc[]

===== Response Fields

This API returns a 204 no content response.

Example:

include::{snippets}/token-management-documentation/set-auth-token-for-domain/1/http-response.adoc[]

==== Getting the token associated to a Domain

A GET request will get a token associated with a domain.

===== Path Parameters

include::{snippets}/token-management-documentation/get-auth-token-for-domain/1/path-parameters.adoc[]

Example:

include::{snippets}/token-management-documentation/get-auth-token-for-domain/1/http-request.adoc[]


===== Response Fields

This API returns a token with these fields:

include::{snippets}/token-management-documentation/get-auth-token-for-domain/1/response-fields.adoc[]

Example:

include::{snippets}/token-management-documentation/get-auth-token-for-domain/1/http-response.adoc[]


=== User Management Service

The user management service provides API for authentication and user management. The default port for
the user management service is 15551

==== Authentication

Using the rest api, you can authenticate users given a username and
password.

A post request authenticates a user on a domain.

===== Request Fields

include::{snippets}/authentication-documentation/authentication/1/request-fields.adoc[]


===== Path Parameters
include::{snippets}/authentication-documentation/authentication/1/path-parameters.adoc[]

Example:

include::{snippets}/authentication-documentation/authentication/1/http-request.adoc[]

===== Response Fields

This API returns a JSON response with the following fields:

include::{snippets}/authentication-documentation/authentication/1/response-fields.adoc[]

Example:

include::{snippets}/authentication-documentation/authentication/1/http-response.adoc[]

==== Managing Domains

A client application references users in one domain. A domain is referenced by a domain id. Applications
can share the same user base by using the same domain id.

===== Security

If token security is enabled, the domain api can be accessed with the admin token.

Token security is enabled by default. To disable, set the environment property `mmadu.domain.api-security-enabled`
to `false`.

===== Creating A domain

A POST request will create a domain

====== Request Fields

include::{snippets}/domain-management-documentation/create-a-domain/1/request-fields.adoc[]

Example:

include::{snippets}/domain-management-documentation/create-a-domain/1/http-request.adoc[]

====== Response Fields

This API returns a HTTP 201 CREATED response with an empty body.

===== Getting a domain with an ID


A GET request will get a domain with an ID.

====== Path Parameters

include::{snippets}/domain-management-documentation/get-a-domain-by-id/1/path-parameters.adoc[]

Example:

include::{snippets}/domain-management-documentation/get-a-domain-by-id/1/http-request.adoc[]


====== Response Fields

This API returns an AppDomain with these fields:

include::{snippets}/domain-management-documentation/get-a-domain-by-id/1/response-fields.adoc[]

Example:

include::{snippets}/domain-management-documentation/get-a-domain-by-id/1/http-response.adoc[]

===== Getting All Domains

A GET request will get all domains.

Example:

include::{snippets}/domain-management-documentation/getting-all-domains/1/http-request.adoc[]


====== Response Fields

This API returns a list of all domains with these fields:

include::{snippets}/domain-management-documentation/getting-all-domains/1/response-fields.adoc[]

Example:

include::{snippets}/domain-management-documentation/getting-all-domains/1/http-response.adoc[]

===== Updating A Domain with an ID

A PATCH request will update a domain with an ID.

====== Path Parameters

include::{snippets}/domain-management-documentation/updating-a-domain/1/path-parameters.adoc[]

Example:

include::{snippets}/domain-management-documentation/updating-a-domain/1/http-request.adoc[]


====== Response Fields

This API returns a HTTP 204 NO CONTENT response.

Example:

include::{snippets}/domain-management-documentation/updating-a-domain/1/http-response.adoc[]

===== Removing A Domain

A DELETE request will remove a domain with an ID.

====== Path Parameters

include::{snippets}/domain-management-documentation/deleting-a-domain-by-id/1/path-parameters.adoc[]

Example:

include::{snippets}/domain-management-documentation/deleting-a-domain-by-id/1/http-request.adoc[]

====== Response Fields

This API returns a HTTP 204 NO CONTENT response.

Example:

include::{snippets}/domain-management-documentation/deleting-a-domain-by-id/1/http-response.adoc[]

==== Users

This contains user information for a specific user. A user could have a username, password, roles,
authorities and any other properties that the client deems fit.


==== Creating A User

A POST request will create a user.

===== Fixed Request Fields

include::{snippets}/user-management-documentation/create-user/1/request-fields.adoc[]

Example:

include::{snippets}/user-management-documentation/create-user/1/http-request.adoc[]

As seen in the example,  you can also add custom properties like the "color" property.


===== Response Fields

This API returns a HTTP 201 CREATED response with an empty body.


==== Getting A User with an ID

A GET request will get a user with an ID.

===== Path Parameters

include::{snippets}/user-management-documentation/getting-a-user-by-id/1/path-parameters.adoc[]

Example:

include::{snippets}/user-management-documentation/getting-a-user-by-id/1/http-request.adoc[]


===== Response Fields

This API returns an AppUser with these fields as well as custom fields provided by the client:

include::{snippets}/user-management-documentation/getting-a-user-by-id/1/response-fields.adoc[]

Example:

include::{snippets}/user-management-documentation/getting-a-user-by-id/1/http-response.adoc[]

As you can see, this user has two extra properties: `favourite-color` and  `country`.


==== Getting All Users In a Domain

A GET request will get all users regardless of domains.

===== Request Parameters

The request includes page information to request for particular sets in the list.

include::{snippets}/user-management-documentation/getting-all-users/1/request-parameters.adoc[]

Example:

include::{snippets}/user-management-documentation/getting-all-users/1/http-request.adoc[]


===== Response Fields

This API returns a list of all users with the fields below. The response also has
fields that display the page information of result. These fields are shown in the example
response and are self explanatory.

include::{snippets}/user-management-documentation/getting-all-users/1/response-fields.adoc[]

Example:

include::{snippets}/user-management-documentation/getting-all-users/1/http-response.adoc[]

==== Removing A User with an ID

A DELETE request will remove a user with an ID.

===== Path Parameters

include::{snippets}/user-management-documentation/deleting-a-user-by-id/1/path-parameters.adoc[]

Example:

include::{snippets}/user-management-documentation/deleting-a-user-by-id/1/http-request.adoc[]


===== Response Fields

This API returns a HTTP 204 NO CONTENT response.

Example:

include::{snippets}/user-management-documentation/deleting-a-user-by-id/1/http-response.adoc[]

==== Updating A User with an ID

A PUT request will update a user with an ID. Not, this api will completely overwrite the properties of the
existing user. There are no partial updates.

===== Path Parameters

include::{snippets}/user-management-documentation/updating-user-properties/1/path-parameters.adoc[]

Example:

include::{snippets}/user-management-documentation/updating-user-properties/1/http-request.adoc[]


===== Response Fields

This API returns a HTTP 204 NO CONTENT response.

Example:

include::{snippets}/user-management-documentation/updating-user-properties/1/http-response.adoc[]

==== Getting A User with a username and domain id

A GET request will get a user with the specified username and domain id.

===== Path Parameters

include::{snippets}/user-management-documentation/getting-a-user-by-username-and-domain/1/path-parameters.adoc[]

===== Request Parameters

include::{snippets}/user-management-documentation/getting-a-user-by-username-and-domain/1/request-parameters.adoc[]

Example:

include::{snippets}/user-management-documentation/getting-a-user-by-username-and-domain/1/http-request.adoc[]


===== Response Fields

This API returns an AppUser with the fields below and other custom fields provided by the domain client.

include::{snippets}/user-management-documentation/getting-a-user-by-username-and-domain/1/response-fields.adoc[]

Example:

include::{snippets}/user-management-documentation/getting-a-user-by-username-and-domain/1/http-response.adoc[]

==== Querying Users

A GET request can search for users by username, and other custom fields created by the client.

NOTE: Query string can only support custom string, integer and boolean fields currently.

WARNING: Ensure to put individual criteria in parenthesis

===== Request Parameters

The request includes page information to request for particular sets in the list.

include::{snippets}/user-management-documentation/querying-users/1/request-parameters.adoc[]

Example:

include::{snippets}/user-management-documentation/querying-users/1/http-request.adoc[]


===== Response Fields

This API returns a list of all users with the fields below. The response also has
fields that display the page information of result. These fields are shown in the example
response and are self explanatory.

include::{snippets}/user-management-documentation/querying-users/1/response-fields.adoc[]

Example:

include::{snippets}/user-management-documentation/querying-users/1/http-response.adoc[]

==== Partial User update

A PATCH request can update users partially based on a query criteria

NOTE: Query string can only support custom string, integer and boolean fields currently.

WARNING: Ensure to put individual criteria in parenthesis

===== Path Parameters

include::{snippets}/user-management-documentation/updating-users-by-query/1/path-parameters.adoc[]

===== Request

The PATCH request accepts a query string and an array of update operations.

include::{snippets}/user-management-documentation/updating-users-by-query/1/request-fields.adoc[]

Example:

include::{snippets}/user-management-documentation/updating-users-by-query/1/http-request.adoc[]

===== Response Fields

The API returns 204 No content for a successful update.

Example:

include::{snippets}/user-management-documentation/updating-users-by-query/1/http-response.adoc[]


=== Registration Service

The registration service provides an api to access the registration page for a domain. The registration page
generates a form from the configured fields and field types of a domain.

==== Displaying the registration form

The registration form can be accessed in the browser using the url:

----
http://[registration-host]:[registration-port]/[domain-id]/register
----

For example, accessing the default domain with the default configuration can be done
by entering the url below on your browser.

----
http://localhost:1552/0/register
----

The registration services redirects to the defaultRedirectionUrl specified in the registration profile for
this domain. To specify a url to redirect to, add the redirectUrl parameter

----
http://localhost:1552/0/register?redirectUrl=http://myapp.com
----
==== Customizing Registration Forms

Registration forms for a domain can be customized by adding and removing fields and field types.
The registration service ensures that form fields are created for each field.

==== Registration Profiles

Each domain has a registration profile object that is used for configuring the applications behaviour during
registration.

NOTE: There can be only one registration profile for a domain.

===== Creating a Registration Profile

A POST Request will create a registration profile.

====== Fixed Request Fields

include::{snippets}/registration-profile-documentation/create-registration-profile/1/request-fields.adoc[]

Example:

include::{snippets}/registration-profile-documentation/create-registration-profile/1/http-request.adoc[]

====== Response Fields

This API returns a HTTP 201 CREATED response with an empty body.

===== Obtaining Registration Profile by Profile ID

A GET Request will return a registration profile with its ID

====== Path Parameters

include::{snippets}/registration-profile-documentation/get-registration-profile-by-id/1/path-parameters.adoc[]

Example:

include::{snippets}/registration-profile-documentation/get-registration-profile-by-id/1/http-request.adoc[]


===== Response Fields

This API returns the registration profile with the following fields:

include::{snippets}/registration-profile-documentation/get-registration-profile-by-id/1/response-fields.adoc[]

Example:

include::{snippets}/registration-profile-documentation/get-registration-profile-by-id/1/http-response.adoc[]


===== Updating Registration Profile by ID

A PATCH Request will update a registration profile. The example below updates the defaultRegistrationUrl property.

====== Path Parameters

include::{snippets}/registration-profile-documentation/update-registration-profile-by-id/1/path-parameters.adoc[]

Example:

include::{snippets}/registration-profile-documentation/update-registration-profile-by-id/1/http-request.adoc[]


====== Response Fields

This API returns a HTTP 204 NO CONTENT response.

Example:

include::{snippets}/registration-profile-documentation/update-registration-profile-by-id/1/http-response.adoc[]


===== Deleting a Registration Profile by ID

A DELETE request will delete a registration profile.

WARNING: Deleting a registration profile will remote all fields associated with the profile and a registration page
for that domain will be unavailable.

====== Path Parameters

include::{snippets}/registration-profile-documentation/delete-registration-profile-by-id/1/path-parameters.adoc[]

Example:

include::{snippets}/registration-profile-documentation/delete-registration-profile-by-id/1/http-request.adoc[]

====== Response Fields

This API returns a HTTP 204 NO CONTENT response.

Example:

include::{snippets}/registration-profile-documentation/delete-registration-profile-by-id/1/http-response.adoc[]

==== Field Types

Field type objects specify the properties of a field type in the registration form. You can create a field type that
can be used by fields in a registration form.

See <<defining-markup-for-fields, Defining Markup for fields>> for more information on how to customize field types.

==== Creating a field Type

A POST request will create a field type

====== Request Fields

include::{snippets}/field-types-documentation/create-field-types/1/request-fields.adoc[]

Example:

include::{snippets}/field-types-documentation/create-field-types/1/http-request.adoc[]

====== Response Fields

This API returns a HTTP 201 CREATED response with an empty body.

===== Getting a field type with an ID

A GET request will get a field type with an ID.

====== Path Parameters

include::{snippets}/field-types-documentation/get-field-type-by-id/1/path-parameters.adoc[]

Example:

include::{snippets}/field-types-documentation/get-field-type-by-id/1/http-request.adoc[]


====== Response Fields

This API returns a FieldType object with these fields:

include::{snippets}/field-types-documentation/get-field-type-by-id/1/response-fields.adoc[]

Example:

include::{snippets}/field-types-documentation/get-field-type-by-id/1/http-response.adoc[]

===== Getting All Field Types

A GET request will get all field types.

Example:

include::{snippets}/field-types-documentation/get-all-field-types/1/http-request.adoc[]


====== Response Fields

This API returns a list of all field types with these fields:

include::{snippets}/field-types-documentation/get-all-field-types/1/response-fields.adoc[]

Example:

include::{snippets}/field-types-documentation/get-all-field-types/1/http-response.adoc[]

===== Updating A Field Type

A PATCH request will update a field type

====== Path Parameters

include::{snippets}/field-types-documentation/update-field-type-by-id/1/path-parameters.adoc[]

Example:

include::{snippets}/field-types-documentation/update-field-type-by-id/1/http-request.adoc[]


====== Response Fields

This API returns a HTTP 204 NO CONTENT response.

Example:

include::{snippets}/field-types-documentation/update-field-type-by-id/1/http-response.adoc[]

===== Removing A Field Type

A DELETE request will remove a field type.

====== Path Parameters

include::{snippets}/field-types-documentation/delete-field-type-by-id/1/path-parameters.adoc[]

Example:

include::{snippets}/field-types-documentation/delete-field-type-by-id/1/http-request.adoc[]

====== Response Fields

This API returns a HTTP 204 NO CONTENT response.

Example:

include::{snippets}/field-types-documentation/delete-field-type-by-id/1/http-response.adoc[]


==== Fields

Fields contain information used in rendering each field in a registration form. Fields utilize properties
of their field types in order to render an adequate representation of the field. Fields also specify the user property
that the input field is bound to. Fields can override and extend certain properties of the field types.

See <<defining-markup-for-fields, Defining Markup for fields>> for more information on how to customize fields.

==== Creating a field

A POST request will create a field

====== Request Fields

include::{snippets}/fields-documentation/create-fields/1/request-fields.adoc[]

Example:

include::{snippets}/fields-documentation/create-fields/1/http-request.adoc[]

====== Response Fields

This API returns a HTTP 201 CREATED response with an empty body.

===== Getting a field type with an ID

A GET request will get a field with an ID.

====== Path Parameters

include::{snippets}/fields-documentation/get-field-by-id/1/path-parameters.adoc[]

Example:

include::{snippets}/fields-documentation/get-field-by-id/1/http-request.adoc[]


====== Response Fields

This API returns a Field object with these fields:

include::{snippets}/fields-documentation/get-field-by-id/1/response-fields.adoc[]

Example:

include::{snippets}/fields-documentation/get-field-by-id/1/http-response.adoc[]

===== Getting All Fields in Domain

A GET request will get all fields in a domain.

====== Request Parameters

include::{snippets}/fields-documentation/get-fields-by-domain/1/request-parameters.adoc[]

Example:

include::{snippets}/fields-documentation/get-fields-by-domain/1/http-request.adoc[]


====== Response Fields

This API returns a list of all fields with these properties:

include::{snippets}/fields-documentation/get-fields-by-domain/1/response-fields.adoc[]

Example:

include::{snippets}/fields-documentation/get-fields-by-domain/1/http-response.adoc[]

===== Updating A Field

A PATCH request will update a field

====== Path Parameters

include::{snippets}/fields-documentation/update-field-by-id/1/path-parameters.adoc[]

Example:

include::{snippets}/fields-documentation/update-field-by-id/1/http-request.adoc[]


====== Response Fields

This API returns a HTTP 204 NO CONTENT response.

Example:

include::{snippets}/fields-documentation/update-field-by-id/1/http-response.adoc[]

===== Removing A Field

A DELETE request will remove a field.

====== Path Parameters

include::{snippets}/fields-documentation/update-field-by-id/1/path-parameters.adoc[]

Example:

include::{snippets}/fields-documentation/update-field-by-id/1/http-request.adoc[]

====== Response Fields

This API returns a HTTP 204 NO CONTENT response.

Example:

include::{snippets}/fields-documentation/update-field-by-id/1/http-response.adoc[]

[#defining-markup-for-fields]
==== Defining Markup for Fields

You define how you want your registration fields by configuring fields and field types. The markup property in
the field type is used to define the markup of that specific field type. An age field type markup can be defined
as shown:

[source,html]
----
<label for='$field.name' class='sr-only'>$field.label</label>
<input type='number' id='$field.name' name='$field.name' class='form-control'
placeholder='$field.placeholder' $maxValue $minValue autofocus $required $inputField $inputStyle $errorStyle >
$errorDisplay"
----

Mmadu registration service uses apache velocity to generate markup for fields. It provies the following in
the template context for use in defining fields. You reference context objects by adding the `$` prefix. For example,
the `$field.name` returns the name property in the field object.

|===
|Object Name |Description

|field
|The field object

|type
|The field type object

|inputField
|Input attribute and value that marks an element as a model input

|inputStyle
|style attribute, any element with this property will have the field type style property appended to that element

|errorStyle
|style attribute, any element with this property will have the style appended with the error style when the field contains errors

|errorDisplay
|HTML markup for displaying field errors

|maxValue
|max attribute, any element with this will have the max attribute set to the max value of the field type

|minValue
|min attribute, any element with this will have the min attribute set to the min value of the field type
|===

