from geraldoyudo/mmadu-registration:1.3.0-RELEASE

COPY application.yml ./

CMD ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Xmx125m", "-jar","./mmadu-registration-1.3.0-RELEASE.jar"]