from geraldoyudo/mmadu-user-registration:1.2.1-SNAPSHOT

COPY application.yml ./

CMD ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Xmx125m", "-jar","./mmadu-user-registration-1.2.1-SNAPSHOT.jar"]