from geraldoyudo/mmadu-token-service:1.3.1-SNAPSHOT

COPY application.yml ./

CMD ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Xmx125m", "-jar","./mmadu-token-service-1.3.1-SNAPSHOT.jar"]