from geraldoyudo/mmadu-user-service:1.3.1-SNAPSHOT

COPY application.yml ./

CMD ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Xmx125m", "-jar","./mmadu-user-service-1.3.1-SNAPSHOT.jar"]