= Getting Started Guides
:showtitle:
:page-title: Mmadu Service
:page-description: User Management Service
:icons: font
:page-root: 
:imagesrootdir: {page-root}/images
:version: master
:page-layout: guide-list

Mmadu can be easily started with docker compose.

== Using Mmadu

Mmadu aims to be highly flexible and customizable. Mmadu is made up of different
components that enables developers to pick and choose which one they need for their application.

Currently, Mmadu is made up of the following:

. Mmadu User Service
. Mmadu Registration
. Mmadu Identity

== Getting Started with Docker

To run Mmadu with all the services, use the docker-compose file:

. Create a folder (we will use mmadu as the created folder)
+
[source,sh]
----
mkdir mmadu && cd mmadu
----
. Download the https://raw.githubusercontent.com/geraldoyudo/mmadu/{version}/docker/docker-compose.yml[docker compose file]
+
[source,sh]
[subs="attributes"]
----
wget https://raw.githubusercontent.com/geraldoyudo/mmadu/{version}/docker/docker-compose.yml
----
. Download the https://raw.githubusercontent.com/geraldoyudo/mmadu/{version}/docker/.env[default environment file]
+
[source,sh]
[subs="attributes"]
----
wget https://raw.githubusercontent.com/geraldoyudo/mmadu/{version}/docker/.env
----
. Make the necessary modifications to suite your configuration (you can use it as is)
. Start the services
+
[source,sh]
----
docker-compose up
----

== Starting Your Journey

Click the Guides for quick tutorials on Mmadu.